// Copyright Hkt Studios, Inc. All Rights Reserved.

#include "HktStoryEditorLibrary.h"

#if WITH_EDITOR

#include "HktStoryJsonLoader.h"
#include "HktStoryJsonParser.h"
#include "HktStoryModule.h"
#include "HktCoreEventLog.h"
#include "Settings/HktRuntimeGlobalSetting.h"
#include "GameplayTagsEditorModule.h"
#include "GameplayTagsManager.h"
#include "Modules/ModuleManager.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

DEFINE_LOG_CATEGORY_STATIC(LogHktStoryEditor, Log, All);

namespace
{
	// Story JSON 파일을 파싱하면서 ResolveTagFunc에 들어오는 모든 태그 문자열을 수집한다.
	// 등록 부작용 없이 이름만 모으는 dry-run.
	void CollectTagsFromDirectory(const FString& Dir, TSet<FString>& OutTags)
	{
		if (!IFileManager::Get().DirectoryExists(*Dir))
		{
			return;
		}
		TArray<FString> JsonFiles;
		IFileManager::Get().FindFilesRecursive(JsonFiles, *Dir, TEXT("*.json"), true, false);

		for (const FString& File : JsonFiles)
		{
			FString JsonStr;
			if (!FFileHelper::LoadFileToString(JsonStr, *File))
			{
				continue;
			}
			auto Recorder = [&OutTags](const FString& TagStr) -> FGameplayTag
			{
				if (!TagStr.IsEmpty())
				{
					OutTags.Add(TagStr);
				}
				return FGameplayTag::RequestGameplayTag(FName(*TagStr), /*ErrorIfNotFound=*/false);
			};
			FHktStoryJsonParser::Get().ParseAndBuild(JsonStr, Recorder);
		}
	}

	// IGameplayTagsEditorModule::AddNewGameplayTagToINI는 TagSourceName이 이미 등록된
	// 소스여야 동작한다. Config/Tags/ 안의 ini 파일은 GameplayTagsManager가 부팅 시
	// AddTagIniSearchPath로 자동 스캔하지만, 신규 파일은 빈 stub로 만들어두고 검색 경로를
	// 강제 재스캔해서 소스 등록이 보장되도록 한다.
	void EnsureTagSourceRegistered(const FString& IniFileName, const FString& IniPath)
	{
		if (!IFileManager::Get().FileExists(*IniPath))
		{
			IFileManager::Get().MakeDirectory(*FPaths::GetPath(IniPath), /*Tree=*/true);
			const FString Stub =
				TEXT("; Auto-generated by UHktStoryEditorLibrary — do not edit manually.\n")
				TEXT("[/Script/GameplayTags.GameplayTagsList]\n");
			FFileHelper::SaveStringToFile(Stub, *IniPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
		}

		// AddTagIniSearchPath는 idempotent하며, 신규 파일이 있으면 GameplayTagsManager가
		// 그것을 FGameplayTagSource로 등록한다.
		const FString SearchDir = FPaths::GetPath(IniPath);
		UGameplayTagsManager::Get().AddTagIniSearchPath(SearchDir);
	}
}

int32 UHktStoryEditorLibrary::RegenerateStoryTagsAndReload()
{
	const UHktRuntimeGlobalSetting* Settings = GetDefault<UHktRuntimeGlobalSetting>();
	if (!Settings || Settings->StoryDirectories.Num() == 0)
	{
		UE_LOG(LogHktStoryEditor, Warning,
			TEXT("No StoryDirectories configured in HktRuntimeGlobalSetting"));
		return 0;
	}

	// 1) JSON 스캔 → 태그 문자열 수집
	TSet<FString> Tags;
	for (const FDirectoryPath& Dir : Settings->StoryDirectories)
	{
		if (!Dir.Path.IsEmpty())
		{
			CollectTagsFromDirectory(Dir.Path, Tags);
		}
	}

	if (Tags.Num() == 0)
	{
		UE_LOG(LogHktStoryEditor, Warning, TEXT("No tags collected from Story JSON files"));
		return 0;
	}

	// 2) 대상 ini 파일이 GameplayTagsManager에 소스로 등록되도록 보장
	const FString IniFileName = TEXT("HktStoryTags.ini");
	const FString IniPath = FPaths::ProjectConfigDir() / TEXT("Tags") / IniFileName;
	EnsureTagSourceRegistered(IniFileName, IniPath);

	// 3) 각 태그를 GameplayTagsEditor 모듈을 통해 등록 — ini 쓰기 + Manager 등록 + 트리 갱신을 한 번에 처리.
	IGameplayTagsEditorModule& EditorModule = IGameplayTagsEditorModule::Get();
	UGameplayTagsManager& Manager = UGameplayTagsManager::Get();

	int32 NewlyAdded = 0;
	int32 AlreadyPresent = 0;
	int32 FailedCount = 0;
	TArray<FString> Sorted = Tags.Array();
	Sorted.Sort();

	for (const FString& TagStr : Sorted)
	{
		if (TagStr.IsEmpty())
		{
			continue;
		}

		const FGameplayTag Existing = Manager.RequestGameplayTag(FName(*TagStr), /*ErrorIfNotFound=*/false);
		if (Existing.IsValid())
		{
			++AlreadyPresent;
			continue;
		}

		const bool bOk = EditorModule.AddNewGameplayTagToINI(
			TagStr,
			TEXT("Auto-registered from Story JSON"),
			FName(*IniFileName));

		if (bOk)
		{
			++NewlyAdded;
		}
		else
		{
			++FailedCount;
			UE_LOG(LogHktStoryEditor, Warning, TEXT("AddNewGameplayTagToINI failed for tag: %s"), *TagStr);
		}
	}

	// 4) 트리 강제 갱신 (AddNewGameplayTagToINI가 내부적으로 broadcast하지만, 일괄 추가 후
	//    한 번 더 호출해 ResolveTag 일관성을 보장)
	Manager.EditorRefreshGameplayTagTree();

	UE_LOG(LogHktStoryEditor, Log,
		TEXT("Story tag regen → total=%d, newly added=%d, already present=%d, failed=%d (ini: %s)"),
		Tags.Num(), NewlyAdded, AlreadyPresent, FailedCount, *IniPath);

	// 5) Story 재로드 (이제 모든 태그가 유효 → ResolveTagOrWarn 경고 없음)
	FHktStoryModule::ReloadAllStories();

	HKT_EVENT_LOG(HktLogTags::Story, EHktLogLevel::Info, EHktLogSource::Server,
		FString::Printf(TEXT("Story tags regenerated: +%d / total %d"), NewlyAdded, Tags.Num()));

	return NewlyAdded;
}

#endif // WITH_EDITOR
