// Semantic Identifier — 공통(몸·이동·행동·명령·링크) 도메인분.
// 어느 트랙의 전용도 아닌 식별자만 둔다. 트랙 소유 식별자는 자기 파일에 —
// 새 식별자는 이 파일 끝에 더한다 — 소비처는 언제나 protocol/semantic-id 하나만 본다.
// 소비처는 언제나 protocol/semantic-id 하나만 import 한다.

export const RULE_MOVE = 'RULE-MOVE-001';
export const RULE_MOVE_PROGRESS = 'RULE-MOVE-PROGRESS-001';
export const RULE_ACTION_BEGIN = 'RULE-ACTION-BEGIN-001';
export const RULE_ACTION_PROGRESS = 'RULE-ACTION-PROGRESS-001';
export const RULE_BODY_PUSH = 'RULE-BODY-PUSH-001';
export const RULE_BODY_MOMENTUM = 'RULE-BODY-MOMENTUM-001';
export const RULE_BODY_FACING = 'RULE-BODY-FACING-001';
export const RULE_MOVE_MODE = 'RULE-MOVE-MODE-001';
export const RULE_ATTRIBUTE_SET = 'RULE-ATTRIBUTE-SET-001';
export const RULE_NPC_DECIDE = 'RULE-NPC-DECIDE-001';

export const INTENT_MOVE = 'INTENT-MOVE-001';
export const INTENT_ACTION_STATE = 'INTENT-ACTION-STATE-001';
export const INTENT_ACTION_PROGRESS = 'INTENT-ACTION-PROGRESS-001';
export const INTENT_ACTION_EXCLUSIVE = 'INTENT-ACTION-EXCLUSIVE-001';
export const INTENT_NPC_AUTONOMY = 'INTENT-NPC-AUTONOMY-001';
export const INTENT_CHARACTER_KIND = 'INTENT-CHARACTER-KIND-001';
export const INTENT_MOTION_OBSERVE = 'INTENT-MOTION-OBSERVE-001';
export const INTENT_LINK_ROUNDTRIP = 'INTENT-LINK-ROUNDTRIP-001';
export const INTENT_LINK_FLOW = 'INTENT-LINK-FLOW-001';
export const INTENT_LINK_EFFORT = 'INTENT-LINK-EFFORT-001';
export const INTENT_LINK_BINDING_VISIBLE = 'INTENT-LINK-BINDING-VISIBLE-001';
export const INTENT_LINK_ALWAYS_SHOWN = 'INTENT-LINK-ALWAYS-SHOWN-001';
export const INTENT_BODY_OCCUPY = 'INTENT-BODY-OCCUPY-001';
export const INTENT_BODY_PUSH = 'INTENT-BODY-PUSH-001';
export const INTENT_BODY_MOMENTUM = 'INTENT-BODY-MOMENTUM-001';
export const INTENT_ACTION_COLLIDER = 'INTENT-ACTION-COLLIDER-001';
export const INTENT_COLLISION_OBSERVE = 'INTENT-COLLISION-OBSERVE-001';
export const INTENT_BODY_FACING = 'INTENT-BODY-FACING-001';
export const INTENT_RUN = 'INTENT-RUN-001';
export const INTENT_MODIFIER_COMPOSE = 'INTENT-MODIFIER-COMPOSE-001';
export const INTENT_TEMPO_MOVE = 'INTENT-TEMPO-MOVE-001';
export const INTENT_TEMPO_ACTION = 'INTENT-TEMPO-ACTION-001';
export const INTENT_ENTITY_IDENTITY = 'INTENT-ENTITY-IDENTITY-001';
export const INTENT_ENTITY_OBSERVE = 'INTENT-ENTITY-OBSERVE-001';
export const INTENT_SELF_OBSERVE = 'INTENT-SELF-OBSERVE-001';
export const INTENT_ATTRIBUTE_OBSERVE = 'INTENT-ATTRIBUTE-OBSERVE-001';
export const INTENT_ATTRIBUTE_MUTATE = 'INTENT-ATTRIBUTE-MUTATE-001';
export const INTENT_COMMAND_CATALOG = 'INTENT-COMMAND-CATALOG-001';
export const INTENT_COMMAND_INVOKE = 'INTENT-COMMAND-INVOKE-001';
export const INTENT_COMMAND_DISCOVER = 'INTENT-COMMAND-DISCOVER-001';
export const INTENT_COMMAND_GUIDED = 'INTENT-COMMAND-GUIDED-001';
export const INTENT_COMMAND_HISTORY = 'INTENT-COMMAND-HISTORY-001';
export const INTENT_OBSERVER_COMMAND = 'INTENT-OBSERVER-COMMAND-001';
export const INTENT_ENTITY_ADDRESSABLE = 'INTENT-ENTITY-ADDRESSABLE-001';

// ── 채광 ──────────────────────────────────────────────────────
export const RULE_MINE = 'RULE-MINE-001';
export const RULE_MINE_COMPLETE = 'RULE-MINE-COMPLETE-001';
export const INTENT_MINING = 'INTENT-MINING-001';

// ── 전투 ────────────────────────────────────────
export const RULE_ATTACK = 'RULE-ATTACK-001';
export const RULE_HIT = 'RULE-HIT-001';
export const RULE_SWING_STRIKE = 'RULE-SWING-STRIKE-001';
export const RULE_SKILL_BEGIN = 'RULE-SKILL-BEGIN-001'; // RULE-ATTACK-001 의 일반화
export const RULE_SKILL_BUDGET = 'RULE-SKILL-BUDGET-001';
export const RULE_STRIKE_DAMAGE = 'RULE-STRIKE-DAMAGE-001';
export const RULE_DOWNED = 'RULE-DOWNED-001';
export const RULE_CP_RUN_DRAIN = 'RULE-CP-RUN-DRAIN-001';
export const RULE_STRIKE_EVENT_EXPIRE = 'RULE-STRIKE-EVENT-EXPIRE-001';

export const INTENT_ATTACK = 'INTENT-ATTACK-001';
export const INTENT_ATTACK_HIT = 'INTENT-ATTACK-HIT-001';
export const INTENT_HIT_REACTION = 'INTENT-HIT-REACTION-001';
export const INTENT_SWING_IMPACT = 'INTENT-SWING-IMPACT-001';
export const INTENT_VITALITY = 'INTENT-VITALITY-001';
export const INTENT_SKILL_BUDGET = 'INTENT-SKILL-BUDGET-001';
export const INTENT_SKILL_COST_GATE = 'INTENT-SKILL-COST-GATE-001';
export const INTENT_STRIKE_DAMAGE = 'INTENT-STRIKE-DAMAGE-001';
export const INTENT_DAMAGE_APPLY = 'INTENT-DAMAGE-APPLY-001';
export const INTENT_DOWNED = 'INTENT-DOWNED-001';
export const INTENT_STRIKE_OBSERVE = 'INTENT-STRIKE-OBSERVE-001';

// C001 — Region 사이의 건너기 (02-world R1)
export const RULE_REGION_TRANSIT = 'RULE-REGION-TRANSIT-001';
