// Semantic Identifier — 이 팩의 Runtime 전이 ↔ 설계 역추적용 식별자 (Traceability).
// Engine 소유 식별자(관찰자 인과·Tick·요청 대답)는 protocol-core 에서 다시 내보낸다.

export {
  RULE_OBSERVER_JOIN,
  RULE_OBSERVER_LEAVE,
  RULE_OBSERVER_MARK,
  RULE_REQUEST_REPLY,
  RULE_WORLD_TICK,
  type SemanticIdentifier,
} from '../../../engine/protocol-core/semantic-id';

export const RULE_MOVE = 'RULE-MOVE-001';
export const RULE_MOVE_PROGRESS = 'RULE-MOVE-PROGRESS-001';
export const RULE_MINE = 'RULE-MINE-001';
export const RULE_ACTION_BEGIN = 'RULE-ACTION-BEGIN-001';
export const RULE_ACTION_PROGRESS = 'RULE-ACTION-PROGRESS-001';
export const RULE_ATTACK = 'RULE-ATTACK-001';
export const RULE_HIT = 'RULE-HIT-001';
export const RULE_SWING_STRIKE = 'RULE-SWING-STRIKE-001'; // C006
export const RULE_BODY_PUSH = 'RULE-BODY-PUSH-001'; // C006
export const RULE_BODY_MOMENTUM = 'RULE-BODY-MOMENTUM-001'; // C006
export const RULE_BODY_FACING = 'RULE-BODY-FACING-001'; // C006 R1
export const RULE_MINE_COMPLETE = 'RULE-MINE-COMPLETE-001';
export const RULE_SKILL_BEGIN = 'RULE-SKILL-BEGIN-001'; // C007 (RULE-ATTACK-001 의 일반화)
export const RULE_SKILL_BUDGET = 'RULE-SKILL-BUDGET-001'; // C007
export const RULE_STRIKE_DAMAGE = 'RULE-STRIKE-DAMAGE-001'; // C007
export const RULE_DOWNED = 'RULE-DOWNED-001'; // C007
export const RULE_CP_RUN_DRAIN = 'RULE-CP-RUN-DRAIN-001'; // C007
export const RULE_MOVE_MODE = 'RULE-MOVE-MODE-001'; // C007
export const RULE_STRIKE_EVENT_EXPIRE = 'RULE-STRIKE-EVENT-EXPIRE-001'; // C007
export const RULE_ATTRIBUTE_SET = 'RULE-ATTRIBUTE-SET-001'; // C007 R2
export const RULE_GUARD_BEGIN = 'RULE-GUARD-BEGIN-001'; // C011
export const RULE_GUARD_RELEASE = 'RULE-GUARD-RELEASE-001'; // C011
export const RULE_GUARD_BLOCK = 'RULE-GUARD-BLOCK-001'; // C011
export const RULE_OBSERVE_BEGIN = 'RULE-OBSERVE-BEGIN-001'; // C014
export const RULE_OBSERVE_COMPLETE = 'RULE-OBSERVE-COMPLETE-001'; // C014
export const RULE_OBSERVE_FORGET = 'RULE-OBSERVE-FORGET-001'; // C014
export const RULE_TARGET_SELECT = 'RULE-TARGET-SELECT-001'; // C017
export const RULE_TARGET_CLEAR = 'RULE-TARGET-CLEAR-001'; // C017
export const RULE_TARGET_CLEAR_STALE = 'RULE-TARGET-CLEAR-STALE-001'; // C017
export const RULE_NPC_DECIDE = 'RULE-NPC-DECIDE-001';
export const RULE_CARRY_ADD = 'RULE-CARRY-ADD-001'; // C020
export const RULE_CARRY_LET_GO = 'RULE-CARRY-LET-GO-001'; // C020
export const INTENT_MOVE = 'INTENT-MOVE-001';
export const INTENT_MINING = 'INTENT-MINING-001';
export const INTENT_ITEM_CATALOG = 'INTENT-ITEM-CATALOG-001'; // C020
export const INTENT_USE_COMES_FROM_DECLARATION = 'INTENT-USE-COMES-FROM-DECLARATION-001'; // C020
export const INTENT_CARRY_ROOM = 'INTENT-CARRY-ROOM-001'; // C020
export const INTENT_ACQUIRE_IS_ALL_OR_NOTHING = 'INTENT-ACQUIRE-IS-ALL-OR-NOTHING-001'; // C020
export const INTENT_CARRIED_IS_OBSERVABLE = 'INTENT-CARRIED-IS-OBSERVABLE-001'; // C020
export const INTENT_LET_GO = 'INTENT-LET-GO-001'; // C020
export const INTENT_NO_DEAD_END = 'INTENT-NO-DEAD-END-001'; // C020
export const INTENT_ACTION_STATE = 'INTENT-ACTION-STATE-001';
export const INTENT_ACTION_PROGRESS = 'INTENT-ACTION-PROGRESS-001';
export const INTENT_ACTION_EXCLUSIVE = 'INTENT-ACTION-EXCLUSIVE-001';
export const INTENT_ATTACK = 'INTENT-ATTACK-001';
export const INTENT_ATTACK_HIT = 'INTENT-ATTACK-HIT-001';
export const INTENT_HIT_REACTION = 'INTENT-HIT-REACTION-001';
export const INTENT_NPC_AUTONOMY = 'INTENT-NPC-AUTONOMY-001';
export const INTENT_CHARACTER_KIND = 'INTENT-CHARACTER-KIND-001';
export const INTENT_MOTION_OBSERVE = 'INTENT-MOTION-OBSERVE-001';
export const INTENT_LINK_ROUNDTRIP = 'INTENT-LINK-ROUNDTRIP-001';
export const INTENT_LINK_FLOW = 'INTENT-LINK-FLOW-001';
export const INTENT_LINK_EFFORT = 'INTENT-LINK-EFFORT-001';
export const INTENT_LINK_BINDING_VISIBLE = 'INTENT-LINK-BINDING-VISIBLE-001';
export const INTENT_LINK_ALWAYS_SHOWN = 'INTENT-LINK-ALWAYS-SHOWN-001';
export const INTENT_BODY_OCCUPY = 'INTENT-BODY-OCCUPY-001'; // C006
export const INTENT_BODY_PUSH = 'INTENT-BODY-PUSH-001'; // C006
export const INTENT_BODY_MOMENTUM = 'INTENT-BODY-MOMENTUM-001'; // C006
export const INTENT_ACTION_COLLIDER = 'INTENT-ACTION-COLLIDER-001'; // C006
export const INTENT_SWING_IMPACT = 'INTENT-SWING-IMPACT-001'; // C006
export const INTENT_COLLISION_OBSERVE = 'INTENT-COLLISION-OBSERVE-001'; // C006
export const INTENT_BODY_FACING = 'INTENT-BODY-FACING-001'; // C006 R1
export const INTENT_VITALITY = 'INTENT-VITALITY-001'; // C007
export const INTENT_SKILL_BUDGET = 'INTENT-SKILL-BUDGET-001'; // C007
export const INTENT_SKILL_COST_GATE = 'INTENT-SKILL-COST-GATE-001'; // C007
export const INTENT_RUN = 'INTENT-RUN-001'; // C007
export const INTENT_MODIFIER_COMPOSE = 'INTENT-MODIFIER-COMPOSE-001'; // C007
export const INTENT_STRIKE_DAMAGE = 'INTENT-STRIKE-DAMAGE-001'; // C007
export const INTENT_DAMAGE_APPLY = 'INTENT-DAMAGE-APPLY-001'; // C007
export const INTENT_DOWNED = 'INTENT-DOWNED-001'; // C007
export const INTENT_TEMPO_MOVE = 'INTENT-TEMPO-MOVE-001'; // C007
export const INTENT_TEMPO_ACTION = 'INTENT-TEMPO-ACTION-001'; // C007
export const INTENT_ENTITY_IDENTITY = 'INTENT-ENTITY-IDENTITY-001'; // C007
export const INTENT_ENTITY_OBSERVE = 'INTENT-ENTITY-OBSERVE-001'; // C007
export const INTENT_SELF_OBSERVE = 'INTENT-SELF-OBSERVE-001'; // C007
export const INTENT_STRIKE_OBSERVE = 'INTENT-STRIKE-OBSERVE-001'; // C007
export const INTENT_ATTRIBUTE_OBSERVE = 'INTENT-ATTRIBUTE-OBSERVE-001'; // C007 R2
export const INTENT_ATTRIBUTE_MUTATE = 'INTENT-ATTRIBUTE-MUTATE-001'; // C007 R2
export const INTENT_COMMAND_CATALOG = 'INTENT-COMMAND-CATALOG-001'; // C009
export const INTENT_COMMAND_INVOKE = 'INTENT-COMMAND-INVOKE-001'; // C009
export const INTENT_COMMAND_DISCOVER = 'INTENT-COMMAND-DISCOVER-001'; // C009
export const INTENT_COMMAND_GUIDED = 'INTENT-COMMAND-GUIDED-001'; // C009
export const INTENT_COMMAND_HISTORY = 'INTENT-COMMAND-HISTORY-001'; // C009
export const INTENT_OBSERVER_COMMAND = 'INTENT-OBSERVER-COMMAND-001'; // C009
export const INTENT_ENTITY_ADDRESSABLE = 'INTENT-ENTITY-ADDRESSABLE-001'; // C009
export const INTENT_GUARD_STANCE = 'INTENT-GUARD-STANCE-001'; // C011
export const INTENT_GUARD_GATE = 'INTENT-GUARD-GATE-001'; // C011
export const INTENT_GUARD_RESTRICT = 'INTENT-GUARD-RESTRICT-001'; // C011
export const INTENT_GUARD_DIRECTION = 'INTENT-GUARD-DIRECTION-001'; // C011
export const INTENT_GUARD_MITIGATE = 'INTENT-GUARD-MITIGATE-001'; // C011
export const INTENT_GUARD_COST = 'INTENT-GUARD-COST-001'; // C011
export const INTENT_GUARD_IMPACT_KEPT = 'INTENT-GUARD-IMPACT-KEPT-001'; // C011
export const INTENT_GUARD_COLLAPSE = 'INTENT-GUARD-COLLAPSE-001'; // C011
export const INTENT_GUARD_OBSERVE = 'INTENT-GUARD-OBSERVE-001'; // C011
export const INTENT_GUARD_BREAKDOWN = 'INTENT-GUARD-BREAKDOWN-001'; // C011
export const INTENT_GUARD_COMMANDABLE = 'INTENT-GUARD-COMMANDABLE-001'; // C011
// C014 — 살펴봄. 아는 것이 주어지는 것에서 하는 일이 된다.
export const INTENT_OBSERVE = 'INTENT-OBSERVE-001';
export const INTENT_OBSERVE_KNOWLEDGE = 'INTENT-OBSERVE-KNOWLEDGE-001';
export const INTENT_UNSEEN_CAPABILITY = 'INTENT-UNSEEN-CAPABILITY-001';
export const INTENT_UNSEEN_IS_OBSERVABLE = 'INTENT-UNSEEN-IS-OBSERVABLE-001';
export const INTENT_OBSERVE_FORGET = 'INTENT-OBSERVE-FORGET-001';
