// Semantic Identifier — 공통(몸·이동·행동·명령·링크) 도메인분.
// 어느 트랙의 전용도 아닌 식별자만 둔다. 트랙 소유 식별자는 자기 파일에 —
// 전투는 semantic-id-combat.ts, 아이템은 semantic-id-item.ts (guides/works.md 병렬 규칙).
// 소비처는 언제나 protocol/semantic-id 하나만 import 한다.

export const RULE_MOVE = 'RULE-MOVE-001';
export const RULE_MOVE_PROGRESS = 'RULE-MOVE-PROGRESS-001';
export const RULE_ACTION_BEGIN = 'RULE-ACTION-BEGIN-001';
export const RULE_ACTION_PROGRESS = 'RULE-ACTION-PROGRESS-001';
export const RULE_BODY_PUSH = 'RULE-BODY-PUSH-001'; // C006
export const RULE_BODY_MOMENTUM = 'RULE-BODY-MOMENTUM-001'; // C006
export const RULE_BODY_FACING = 'RULE-BODY-FACING-001'; // C006 R1
export const RULE_MOVE_MODE = 'RULE-MOVE-MODE-001'; // C007
export const RULE_ATTRIBUTE_SET = 'RULE-ATTRIBUTE-SET-001'; // C007 R2
export const RULE_NPC_DECIDE = 'RULE-NPC-DECIDE-001';

export const INTENT_MOVE = 'INTENT-MOVE-001';
export const INTENT_ACTION_STATE = 'INTENT-ACTION-STATE-001';
export const INTENT_ACTION_PROGRESS = 'INTENT-ACTION-PROGRESS-001';
export const INTENT_ACTION_EXCLUSIVE = 'INTENT-ACTION-EXCLUSIVE-001';
export const INTENT_NPC_AUTONOMY = 'INTENT-NPC-AUTONOMY-001';
export const INTENT_CHARACTER_KIND = 'INTENT-CHARACTER-KIND-001';
export const INTENT_MOTION_OBSERVE = 'INTENT-MOTION-OBSERVE-001';
export const INTENT_LINK_ROUNDTRIP = 'INTENT-LINK-ROUNDTRIP-001';
export const INTENT_LINK_FLOW = 'INTENT-LINK-FLOW-001';
export const INTENT_LINK_EFFORT = 'INTENT-LINK-EFFORT-001';
export const INTENT_LINK_BINDING_VISIBLE = 'INTENT-LINK-BINDING-VISIBLE-001';
export const INTENT_LINK_ALWAYS_SHOWN = 'INTENT-LINK-ALWAYS-SHOWN-001';
export const INTENT_BODY_OCCUPY = 'INTENT-BODY-OCCUPY-001'; // C006
export const INTENT_BODY_PUSH = 'INTENT-BODY-PUSH-001'; // C006
export const INTENT_BODY_MOMENTUM = 'INTENT-BODY-MOMENTUM-001'; // C006
export const INTENT_ACTION_COLLIDER = 'INTENT-ACTION-COLLIDER-001'; // C006
export const INTENT_COLLISION_OBSERVE = 'INTENT-COLLISION-OBSERVE-001'; // C006
export const INTENT_BODY_FACING = 'INTENT-BODY-FACING-001'; // C006 R1
export const INTENT_RUN = 'INTENT-RUN-001'; // C007
export const INTENT_MODIFIER_COMPOSE = 'INTENT-MODIFIER-COMPOSE-001'; // C007
export const INTENT_TEMPO_MOVE = 'INTENT-TEMPO-MOVE-001'; // C007
export const INTENT_TEMPO_ACTION = 'INTENT-TEMPO-ACTION-001'; // C007
export const INTENT_ENTITY_IDENTITY = 'INTENT-ENTITY-IDENTITY-001'; // C007
export const INTENT_ENTITY_OBSERVE = 'INTENT-ENTITY-OBSERVE-001'; // C007
export const INTENT_SELF_OBSERVE = 'INTENT-SELF-OBSERVE-001'; // C007
export const INTENT_ATTRIBUTE_OBSERVE = 'INTENT-ATTRIBUTE-OBSERVE-001'; // C007 R2
export const INTENT_ATTRIBUTE_MUTATE = 'INTENT-ATTRIBUTE-MUTATE-001'; // C007 R2
export const INTENT_COMMAND_CATALOG = 'INTENT-COMMAND-CATALOG-001'; // C009
export const INTENT_COMMAND_INVOKE = 'INTENT-COMMAND-INVOKE-001'; // C009
export const INTENT_COMMAND_DISCOVER = 'INTENT-COMMAND-DISCOVER-001'; // C009
export const INTENT_COMMAND_GUIDED = 'INTENT-COMMAND-GUIDED-001'; // C009
export const INTENT_COMMAND_HISTORY = 'INTENT-COMMAND-HISTORY-001'; // C009
export const INTENT_OBSERVER_COMMAND = 'INTENT-OBSERVER-COMMAND-001'; // C009
export const INTENT_ENTITY_ADDRESSABLE = 'INTENT-ENTITY-ADDRESSABLE-001'; // C009
