// Semantic Identifier — 전투(COMBAT 트랙) 도메인분. 타격·기력·막기·앎·지목.
// 트랙이 자기 파일을 소유한다 (guides/works.md 병렬 규칙).
// 소비처는 언제나 protocol/semantic-id 하나만 import 한다.

export const RULE_ATTACK = 'RULE-ATTACK-001';
export const RULE_HIT = 'RULE-HIT-001';
export const RULE_SWING_STRIKE = 'RULE-SWING-STRIKE-001'; // C006
export const RULE_SKILL_BEGIN = 'RULE-SKILL-BEGIN-001'; // C007 (RULE-ATTACK-001 의 일반화)
export const RULE_SKILL_BUDGET = 'RULE-SKILL-BUDGET-001'; // C007
export const RULE_STRIKE_DAMAGE = 'RULE-STRIKE-DAMAGE-001'; // C007
export const RULE_DOWNED = 'RULE-DOWNED-001'; // C007
export const RULE_CP_RUN_DRAIN = 'RULE-CP-RUN-DRAIN-001'; // C007
export const RULE_STRIKE_EVENT_EXPIRE = 'RULE-STRIKE-EVENT-EXPIRE-001'; // C007
export const RULE_GUARD_BEGIN = 'RULE-GUARD-BEGIN-001'; // C011
export const RULE_GUARD_RELEASE = 'RULE-GUARD-RELEASE-001'; // C011
export const RULE_GUARD_BLOCK = 'RULE-GUARD-BLOCK-001'; // C011
export const RULE_OBSERVE_BEGIN = 'RULE-OBSERVE-BEGIN-001'; // C014
export const RULE_OBSERVE_COMPLETE = 'RULE-OBSERVE-COMPLETE-001'; // C014
export const RULE_OBSERVE_FORGET = 'RULE-OBSERVE-FORGET-001'; // C014
export const RULE_TARGET_SELECT = 'RULE-TARGET-SELECT-001'; // C017
export const RULE_TARGET_CLEAR = 'RULE-TARGET-CLEAR-001'; // C017
export const RULE_TARGET_CLEAR_STALE = 'RULE-TARGET-CLEAR-STALE-001'; // C017

export const INTENT_ATTACK = 'INTENT-ATTACK-001';
export const INTENT_ATTACK_HIT = 'INTENT-ATTACK-HIT-001';
export const INTENT_HIT_REACTION = 'INTENT-HIT-REACTION-001';
export const INTENT_SWING_IMPACT = 'INTENT-SWING-IMPACT-001'; // C006
export const INTENT_VITALITY = 'INTENT-VITALITY-001'; // C007
export const INTENT_SKILL_BUDGET = 'INTENT-SKILL-BUDGET-001'; // C007
export const INTENT_SKILL_COST_GATE = 'INTENT-SKILL-COST-GATE-001'; // C007
export const INTENT_STRIKE_DAMAGE = 'INTENT-STRIKE-DAMAGE-001'; // C007
export const INTENT_DAMAGE_APPLY = 'INTENT-DAMAGE-APPLY-001'; // C007
export const INTENT_DOWNED = 'INTENT-DOWNED-001'; // C007
export const INTENT_STRIKE_OBSERVE = 'INTENT-STRIKE-OBSERVE-001'; // C007
export const INTENT_GUARD_STANCE = 'INTENT-GUARD-STANCE-001'; // C011
export const INTENT_GUARD_GATE = 'INTENT-GUARD-GATE-001'; // C011
export const INTENT_GUARD_RESTRICT = 'INTENT-GUARD-RESTRICT-001'; // C011
export const INTENT_GUARD_DIRECTION = 'INTENT-GUARD-DIRECTION-001'; // C011
export const INTENT_GUARD_MITIGATE = 'INTENT-GUARD-MITIGATE-001'; // C011
export const INTENT_GUARD_COST = 'INTENT-GUARD-COST-001'; // C011
export const INTENT_GUARD_IMPACT_KEPT = 'INTENT-GUARD-IMPACT-KEPT-001'; // C011
export const INTENT_GUARD_COLLAPSE = 'INTENT-GUARD-COLLAPSE-001'; // C011
export const INTENT_GUARD_OBSERVE = 'INTENT-GUARD-OBSERVE-001'; // C011
export const INTENT_GUARD_BREAKDOWN = 'INTENT-GUARD-BREAKDOWN-001'; // C011
export const INTENT_GUARD_COMMANDABLE = 'INTENT-GUARD-COMMANDABLE-001'; // C011
// C014 — 살펴봄. 아는 것이 주어지는 것에서 하는 일이 된다.
export const INTENT_OBSERVE = 'INTENT-OBSERVE-001';
export const INTENT_OBSERVE_KNOWLEDGE = 'INTENT-OBSERVE-KNOWLEDGE-001';
export const INTENT_UNSEEN_CAPABILITY = 'INTENT-UNSEEN-CAPABILITY-001';
export const INTENT_UNSEEN_IS_OBSERVABLE = 'INTENT-UNSEEN-IS-OBSERVABLE-001';
export const INTENT_OBSERVE_FORGET = 'INTENT-OBSERVE-FORGET-001';
