// Semantic Identifier — 성장(GROWTH 트랙) 도메인분. 쌓임 · 문턱 · 단계.
// 트랙이 자기 파일을 소유한다 (guides/works.md 병렬 규칙).
// 소비처는 언제나 protocol/semantic-id 하나만 import 한다.

export const RULE_DEEDS_ADD = 'RULE-DEEDS-ADD-001'; // C-GROWTH-001
export const RULE_GROWTH_LEVEL = 'RULE-GROWTH-LEVEL-001'; // C-GROWTH-001 (읽기 판정)

export const INTENT_THE_BODY_KEEPS_WHAT_IT_DID = 'INTENT-THE-BODY-KEEPS-WHAT-IT-DID-001';
export const INTENT_THE_WORLD_ADDS_WHAT_WAS_DONE = 'INTENT-THE-WORLD-ADDS-WHAT-WAS-DONE-001';
export const INTENT_ONLY_REAL_ACTS_COUNT = 'INTENT-ONLY-REAL-ACTS-COUNT-001';
export const INTENT_WHAT_IS_KEPT_ONLY_GROWS = 'INTENT-WHAT-IS-KEPT-ONLY-GROWS-001';
export const INTENT_ENOUGH_IS_A_STEP = 'INTENT-ENOUGH-IS-A-STEP-001';
export const INTENT_THE_STEP_ENTERS_THE_EFFECTIVE_VALUE =
  'INTENT-THE-STEP-ENTERS-THE-EFFECTIVE-VALUE-001';
export const INTENT_WHAT_GROWS_IS_WHAT_THE_CONTEST_READS =
  'INTENT-WHAT-GROWS-IS-WHAT-THE-CONTEST-READS-001';
export const INTENT_THE_ZEROTH_STEP_ADDS_NOTHING = 'INTENT-THE-ZEROTH-STEP-ADDS-NOTHING-001';
export const INTENT_A_STEP_IS_A_SMALL_CHANGE = 'INTENT-A-STEP-IS-A-SMALL-CHANGE-001';
export const INTENT_THE_STEP_OPENS_NOTHING = 'INTENT-THE-STEP-OPENS-NOTHING-001';
export const INTENT_THE_LEDGER_IS_OBSERVED = 'INTENT-THE-LEDGER-IS-OBSERVED-001';
export const INTENT_GROWING_CARRIES_ITS_REASON = 'INTENT-GROWING-CARRIES-ITS-REASON-001';
