// Semantic Identifier — 땅(TERRAIN 트랙) 도메인분. 자리·법칙·거둠.
// 트랙이 자기 파일을 소유한다 (guides/works.md 병렬 규칙).
// 소비처는 언제나 protocol/semantic-id 하나만 import 한다.

export const RULE_GROUND_LAW_APPLY = 'RULE-GROUND-LAW-APPLY-001'; // C-TERRAIN-001

export const INTENT_GROUND_IS_DIVIDED_INTO_PLACES = 'INTENT-GROUND-IS-DIVIDED-INTO-PLACES-001';
export const INTENT_GROUND_LAW_IS_CONDITION_AND_RESULT =
  'INTENT-GROUND-LAW-IS-CONDITION-AND-RESULT-001';
export const INTENT_GROUND_LAW_TAKES_WHILE_YOU_STAY = 'INTENT-GROUND-LAW-TAKES-WHILE-YOU-STAY-001';
export const INTENT_GROUND_LAW_DOES_NOT_CHOOSE_WHOM = 'INTENT-GROUND-LAW-DOES-NOT-CHOOSE-WHOM-001';
export const INTENT_BODY_HOLDS_WHAT_THE_LAND_TAKES = 'INTENT-BODY-HOLDS-WHAT-THE-LAND-TAKES-001';
export const INTENT_THE_LAND_REACHES_LIFE_WHEN_NOTHING_IS_LEFT =
  'INTENT-THE-LAND-REACHES-LIFE-WHEN-NOTHING-IS-LEFT-001';
export const INTENT_GROUND_EXCEPTION_STOPS_THE_LAW = 'INTENT-GROUND-EXCEPTION-STOPS-THE-LAW-001';
export const INTENT_STANDING_IS_THE_WHOLE_INPUT = 'INTENT-STANDING-IS-THE-WHOLE-INPUT-001';
export const INTENT_GROUND_LAW_IS_OBSERVED = 'INTENT-GROUND-LAW-IS-OBSERVED-001';
export const INTENT_GROUND_PLACES_ARE_OBSERVED = 'INTENT-GROUND-PLACES-ARE-OBSERVED-001';
