// Semantic Identifier — Runtime 전이 ↔ 설계 역추적용 식별자 (Traceability)

export const RULE_MOVE = 'RULE-MOVE-001';
export const RULE_MOVE_PROGRESS = 'RULE-MOVE-PROGRESS-001';
export const RULE_MINE = 'RULE-MINE-001';
export const RULE_ACTION_BEGIN = 'RULE-ACTION-BEGIN-001';
export const RULE_ACTION_PROGRESS = 'RULE-ACTION-PROGRESS-001';
export const RULE_ATTACK = 'RULE-ATTACK-001';
export const RULE_ATTACK_COMPLETE = 'RULE-ATTACK-COMPLETE-001';
export const RULE_HIT = 'RULE-HIT-001';
export const RULE_MINE_COMPLETE = 'RULE-MINE-COMPLETE-001';
export const RULE_NPC_DECIDE = 'RULE-NPC-DECIDE-001';

export const INTENT_MOVE = 'INTENT-MOVE-001';
export const INTENT_MINING = 'INTENT-MINING-001';
export const INTENT_ACTION_STATE = 'INTENT-ACTION-STATE-001';
export const INTENT_ACTION_PROGRESS = 'INTENT-ACTION-PROGRESS-001';
export const INTENT_ACTION_EXCLUSIVE = 'INTENT-ACTION-EXCLUSIVE-001';
export const INTENT_ATTACK = 'INTENT-ATTACK-001';
export const INTENT_ATTACK_HIT = 'INTENT-ATTACK-HIT-001';
export const INTENT_HIT_REACTION = 'INTENT-HIT-REACTION-001';
export const INTENT_NPC_AUTONOMY = 'INTENT-NPC-AUTONOMY-001';
export const INTENT_CHARACTER_KIND = 'INTENT-CHARACTER-KIND-001';
export const INTENT_MOTION_OBSERVE = 'INTENT-MOTION-OBSERVE-001';

export type SemanticIdentifier = string;
