export {
  assertAffordance,
  pathToReach,
  resolveAffordances,
  searchReach,
  type ReachSearch,
  type ResolveOptions,
} from './affordance.js';
export {
  blockersInBox,
  blockersOnSegment,
  boxesIntersect,
  boxesOverlap,
  segmentHitsBox,
  type BlockKind,
} from './collision.js';
export { SpatialRejection } from './errors.js';
export { auditPath, findPath, type PathOptions } from './movement.js';
export { SpatialIndex, allCells } from './spatialIndex.js';
export {
  assertLayout,
  barrierOf,
  boxDistance,
  boxOf,
  capabilitiesOf,
  cellBox,
  cellCenter,
  cellKey,
  contains,
  distance,
  extentOf,
  parseCellKey,
  placedEntities,
  positionOf,
  reachOf,
  readVec3,
  sameCell,
  toCell,
} from './transform.js';
export {
  auditOutput,
  buildWorld,
  cellOf,
  createS0Module,
  describeBox,
  executeS0,
  validateInput,
  validateOutput,
  S0_PURPOSE,
  S0_VERSION,
  type S0Input,
  type S0Output,
  type S0Step,
  type S0StepReport,
  type S0World,
} from './module.js';
export {
  ACCESS_ISSUE,
  BARRIER_COMPONENT,
  CAPABILITY_COMPONENT,
  EXTENT_COMPONENT,
  POSITION_COMPONENT,
  REACH_COMPONENT,
  type AccessIssueCode,
  type AccessRejection,
  type Affordance,
  type AffordanceOffer,
  type Barrier,
  type Box,
  type Cell,
  type PathReport,
  type RangeReport,
  type SpatialLayout,
  type Vec3,
} from './types.js';
