// Semantic Identifier — Engine 이 소유하는 Rule/Intent 식별자 (P2 CHANGED).
//
// 여기 있는 것은 세계의 껍데기(관찰자 인과·Tick·요청 대답)의 것뿐이다.
// 게임 의미의 식별자는 각 컨텐츠 팩의 protocol/semantic-id.ts 가 소유한다.

export const RULE_REQUEST_REPLY = 'RULE-REQUEST-REPLY-001'; // C009
export const RULE_WORLD_TICK = 'RULE-WORLD-TICK-001';
export const RULE_OBSERVER_JOIN = 'RULE-OBSERVER-JOIN-001';
export const RULE_OBSERVER_LEAVE = 'RULE-OBSERVER-LEAVE-001';
export const RULE_OBSERVER_MARK = 'RULE-OBSERVER-MARK-001';
export const INTENT_WORLD_CLOCK = 'INTENT-WORLD-CLOCK-001';
export const INTENT_OBSERVER_IDENTITY = 'INTENT-OBSERVER-IDENTITY-001';
export const INTENT_OBSERVER_JOIN = 'INTENT-OBSERVER-JOIN-001';
export const INTENT_OBSERVER_REJOIN = 'INTENT-OBSERVER-REJOIN-001';
export const INTENT_OBSERVER_LEAVE = 'INTENT-OBSERVER-LEAVE-001';
export const INTENT_PER_OBSERVER_PROJECTION = 'INTENT-PER-OBSERVER-PROJECTION-001';
export const INTENT_REQUEST_ATTRIBUTION = 'INTENT-REQUEST-ATTRIBUTION-001';
export const INTENT_OBSERVER_MARK = 'INTENT-OBSERVER-MARK-001';
export const INTENT_REQUEST_REPLY = 'INTENT-REQUEST-REPLY-001'; // C009
export const INTENT_REPLY_CORRESPONDENCE = 'INTENT-REPLY-CORRESPONDENCE-001'; // C009
export type SemanticIdentifier = string;
